name: Postman_Newman_Task
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test-api:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    
    - name: Install dependencies
      run: npm install -g node-pre-gyp
    - name: Install newman
      run: npm install -g newman            
    - name: Install newman report  
      run: npm install -g newman-reporter-htmlextra    
    - name: Run Postman Colection      
      run: npm run 
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: report
        path: testResults/
        retention-days: 30
    - name: Push to repository
      uses: cpina/github-action-push-to-another-repository@main
      if: always()
      env:
        API_TOKEN_GITHUB: ${{ secrets.SECRET_TOKEN }}
      with:
        source-directory: 'testResults'
        destination-github-username: 'txt2021'
        destination-repository-name: 'Postman_Newman_testing'
        user-email: txt2021@gmail.com
        target-branch: report