name: Postman Task
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra


      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          npx newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export ./testResults/report.html
      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
      - name: Push to repository
        uses: cpina/github-action-push-to-another-repository@main
        if: always()
        env:
          API_TOKEN_GITHUB: ${{ secrets.SECRET_TOKEN }}
        with:
          source-directory: 'testResults'
          destination-github-username: 'txt2021'
          destination-repository-name: 'Postman_Newman_testing'
          user-email: txt2021@gmail.com
          target-branch: report
